import { LeaderboardEntry } from '../types';

/**
 * Standard community NEET aspirants seed data for the weekly leaderboard
 */
export const SEED_COMMUNITY_ASPIRANTS: Omit<LeaderboardEntry, 'rank'>[] = [
  {
    uid: 'neet-user-1',
    displayName: 'Aarav Sharma',
    username: 'aarav_aiims',
    targetYear: '2026',
    targetScore: 710,
    avatarBg: '#0F9D58',
    weeklyStudyHours: 44.5,
    weeklyTasksCompleted: 34,
    streakDays: 24,
    prepScore: 98,
    badgeTitle: 'AIR #1 Contender',
    location: 'Kota, Rajasthan',
    isStudyingNow: true,
  },
  {
    uid: 'neet-user-2',
    displayName: 'Sneha Patel',
    username: 'sneha_neet',
    targetYear: '2026',
    targetScore: 705,
    avatarBg: '#E91E63',
    weeklyStudyHours: 42.0,
    weeklyTasksCompleted: 31,
    streakDays: 19,
    prepScore: 94,
    badgeTitle: 'Physics Ninja',
    location: 'Ahmedabad, Gujarat',
    isStudyingNow: false,
  },
  {
    uid: 'neet-user-3',
    displayName: 'Rohan Gupta',
    username: 'rohan_mamc',
    targetYear: '2026',
    targetScore: 695,
    avatarBg: '#7B1FA2',
    weeklyStudyHours: 39.5,
    weeklyTasksCompleted: 29,
    streakDays: 16,
    prepScore: 91,
    badgeTitle: 'Bio Master',
    location: 'Delhi NCR',
    isStudyingNow: true,
  },
  {
    uid: 'neet-user-4',
    displayName: 'Priya Meena',
    username: 'priya_vmmc',
    targetYear: '2026',
    targetScore: 690,
    avatarBg: '#0494F4',
    weeklyStudyHours: 37.0,
    weeklyTasksCompleted: 26,
    streakDays: 14,
    prepScore: 87,
    badgeTitle: 'Streak Champion',
    location: 'Jaipur, Rajasthan',
    isStudyingNow: false,
  },
  {
    uid: 'neet-user-5',
    displayName: 'Kabir Verma',
    username: 'kabir_kgmu',
    targetYear: '2026',
    targetScore: 685,
    avatarBg: '#F4B400',
    weeklyStudyHours: 35.0,
    weeklyTasksCompleted: 24,
    streakDays: 11,
    prepScore: 82,
    badgeTitle: 'Chemistry Whiz',
    location: 'Lucknow, UP',
    isStudyingNow: true,
  },
  {
    uid: 'neet-user-6',
    displayName: 'Ananya Bose',
    username: 'ananya_cmc',
    targetYear: '2026',
    targetScore: 680,
    avatarBg: '#00897B',
    weeklyStudyHours: 33.5,
    weeklyTasksCompleted: 22,
    streakDays: 9,
    prepScore: 78,
    badgeTitle: 'Early Bird',
    location: 'Kolkata, WB',
    isStudyingNow: false,
  },
  {
    uid: 'neet-user-7',
    displayName: 'Tanmay Deshmukh',
    username: 'tanmay_bjmc',
    targetYear: '2026',
    targetScore: 675,
    avatarBg: '#D81B60',
    weeklyStudyHours: 31.0,
    weeklyTasksCompleted: 20,
    streakDays: 8,
    prepScore: 74,
    badgeTitle: 'Night Owl',
    location: 'Pune, Maharashtra',
    isStudyingNow: false,
  },
  {
    uid: 'neet-user-8',
    displayName: 'Meera Nambiar',
    username: 'meera_jipmer',
    targetYear: '2026',
    targetScore: 690,
    avatarBg: '#5E35B1',
    weeklyStudyHours: 29.0,
    weeklyTasksCompleted: 19,
    streakDays: 7,
    prepScore: 70,
    badgeTitle: 'Mock Specialist',
    location: 'Kochi, Kerala',
    isStudyingNow: true,
  },
];
